#!/bin/bash
set -e

BASE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export GIT_SSL_NO_VERIFY=true
mkdir -p ~/.vim/autoload
curl --insecure -fLo ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim

mkdir -p ~/.vim/undo

vim +PlugInstall +qall

# Docker build workaround 
# TODO: different workaround or sed options for mac os
#sed --in-place --follow-symlinks 's/" colorscheme solarized/colorscheme solarized/g' ~/.vimrc
