#!/bin/bash
set -e

BASE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR_NAME=`basename "$BASE"`
if [ -d $BASE/../$BASE_DIR_NAME"_private" ]; then
  BASE_PRIVATE=$BASE/../$BASE_DIR_NAME"_private"
fi

source $BASE/functions

link_configs $BASE
if [ -n "$BASE_PRIVATE" ]; then
  link_configs $BASE_PRIVATE
fi

mkdir -pv ~/bin

link_executables $BASE
if [ -n "$BASE_PRIVATE" ]; then
  link_executables $BASE_PRIVATE
fi

mkdir -pv ~/aliases

link_aliases $BASE
if [ -n "$BASE_PRIVATE" ]; then
  link_aliases $BASE_PRIVATE
fi


if ! which tmux && which tmux-next &> /dev/null; then
  echo '#!/bin/sh' > ~/bin/tmux
  echo 'tmux-next' >> ~/bin/tmux
  chmod +x ~/bin/tmux
fi

# ASDF manager
if [ ! -d ~/.asdf ]; then
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch master
fi

if [ ! -d ~/.zgen ]; then
  git clone https://github.com/tarjoilija/zgen.git ~/.zgen
fi

mkdir -p ~/.zshrc.d
cp $BASE/zshrc.d/* ~/.zshrc.d/

# Install Powerline fonts
curl -L https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf > /tmp/PowerlineSymbols.otf
curl -L https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf > /tmp/10-powerline-symbols.conf

mkdir -p ~/.fonts/
mv /tmp/PowerlineSymbols.otf ~/.fonts/

if which fc-cache &> /dev/null; then
  fc-cache -vf ~/.fonts/
fi

mkdir -p ~/.config/fontconfig/conf.d/
mv /tmp/10-powerline-symbols.conf ~/.config/fontconfig/conf.d/

if which rtorrent &> /dev/null; then
  # Rtorrent folders
  mkdir -p ~/torrents/downloads
  mkdir -p ~/torrents/watch
  mkdir -p ~/torrents/session
fi

$BASE/install-vim
