#!/bin/bash
set -e 

BASE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

for config_to_link in $BASE/ln_*; do
  mkdir -pv $BASE/backup
  config_name=${config_to_link#*_}
  [ -e ~/.$config_name ] && mv -v ~/.$config_name $BASE/backup/.$config_name
  ln -sfv $config_to_link ~/.$config_name
done

mkdir -p ~/bin

for executable in $(find $BASE/bin -type f); do
  mkdir -pv $BASE/backup/bin
  [ -e ~/bin/$executable ] && mv -v ~/bin/$executable $BASE/backup/bin/$executable
  ln -svf $executable ~/bin/$executable
done

if ! which tmux && which tmux-next &> /dev/null
  then
    echo '#!/bin/sh' > ~/bin/tmux
    echo 'tmux-next' >> ~/bin/tmux
    chmod +x ~/bin/tmux
fi

# ASDF manager
if ! which asdf
  then
    git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch master
fi

git clone https://github.com/tarjoilija/zgen.git ~/.zgen
mkdir -p ~/.zshrc.d
cp $BASE/zshrc.d/* ~/.zshrc.d/

# Install Powerline fonts 
curl -L https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf > /tmp/PowerlineSymbols.otf
curl -L https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf > /tmp/10-powerline-symbols.conf

mkdir -p ~/.fonts/
mv /tmp/PowerlineSymbols.otf ~/.fonts/
fc-cache -vf ~/.fonts/

mkdir -p ~/.config/fontconfig/conf.d/
mv /tmp/10-powerline-symbols.conf ~/.config/fontconfig/conf.d/

# Rtorrent folders
mkdir -p ~/torrents/downloads
mkdir -p ~/torrents/watch
mkdir -p ~/torrents/session

$BASE/install-vim
