#!/bin/bash
set -e

BASE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export GIT_SSL_NO_VERIFY=true
mkdir -p ~/.vim/autoload
curl --insecure -fLo ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim

# vimrc
mv -v ~/.vimrc ~/.vimrc.old 2> /dev/null
ln -sf $BASE/ln_vimrc ~/.vimrc

mkdir -p ~/.vim/undo

vim +PlugInstall +qall

# Docker build workaround 
sed -ie 's/" colorscheme solarized/colorscheme solarized/g' ~/.vimrc
