#!/bin/bash

cd $(dirname $BASH_SOURCE)
BASE=$(pwd)

for rc in *rc *config gitignore-global rspec; do
  mkdir -pv bak
  [ -e ~/.$rc ] && mv -v ~/.$rc bak/.$rc
  ln -sfv $BASE/$rc ~/.$rc
done

mkdir -p ~/bin
for bin in $BASE/bin/*; do
  ln -svf $bin ~/bin
done

mkdir -p ~/.antigen
curl -L https://cdn.rawgit.com/zsh-users/antigen/v2.1.1/bin/antigen.zsh > ~/.antigen/antigen.zsh

mkdir -p ~/.zshrc.d
cp zshrc.d/* ~/.zshrc.d/
